spring:
    application:
        name: ace-config
    cloud:
        config:
            server:
                git:
                    uri: https://git.oschina.net/geek_qi/AG-Config.git

server:
    port: 8750 #启动端口

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
